### ISSUE TITLE
[needs discussion] follows namespaces package convention ?

### ISSUE THREAD

**Issue by vincentsarago** [stac-utils/stac-fastapi#115]
with the recent update we've split the module to multiple sub-packages (namespaced). In the current repo architecture those packages are placed at the top-level and then dynamically linked in `/stac-fastapi`. 

While the current structure gives a quick overview of all the sub-packages I'm not sure it's well aligned with the namespace convention.

cc @geospatial-jeff @kylebarron

**Comment by geospatial-jeff** [comment]
It's unfortunate that the symlinks don't resolve in github; in an IDE where they do resolve I think it's an ok pattern.  But this also assumes that you are using an IDE that supports this functionality which I don't think is always the case.  Even when the IDE does resolve it can still cause problems.  For example, the "Find" functionality in PyCharm to look for a particular variable will find that variable in both the `stac-fastapi` as well as the namespace package itself, which is quite confusing.  And the changes you make to `stac-fastapi` aren't tracked - you have to modify the namespace package itself.

All in all I agree that we should move to a more "standard" namespace package setup by moving all of the submodules under a single top-level folder.

**Comment by geospatial-jeff** [comment]
I'm thinking something closer to what is described here https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages

**Comment by vincentsarago** [comment]
I think this is good to close @bitner @geospatial-jeff
