### ISSUE TITLE
Request to /collection/<missing>/items returns 200

### ISSUE THREAD

**Issue by TomAugspurger** [stac-utils/stac-fastapi#120]
If I make a request to an endpoint for a collection that doesn't exists, I get a 404

```python
In [14]: import requests

In [19]: r = requests.get("https://pct-pqe-staging.westeurope.cloudapp.azure.com/stac/v1/collections/not-a-collection")

In [20]: r.status_code
Out[20]: 404
```

But if I make a request to that collection's `/items` I get a 200, and the response includes an empty FeatureCollection.

```python
In [21]: r = requests.get("https://pct-pqe-staging.westeurope.cloudapp.azure.com/stac/v1/collections/not-a-collection/items")

In [22]: r.status_code
Out[22]: 200

In [23]: r.json()
Out[23]:
{'type': 'FeatureCollection',
 'features': [],
 'links': [],
 'context': {'returned': 0, 'matched': 0}}
```

I wanted to verify that this is the expected behavior. I didn't find anything in the API spec, but I admittedly didn't look too closely.

Reported in https://github.com/TomAugspurger/stac-dask-discussion/issues/1

**Comment by geospatial-jeff** [comment]
I also can't find anything in the spec, but this smells funny to me.  I think it would be more RESTful to return a 404 in this case since the resource being requested doesn't exist on the server (an item can't exist outside of a collection).

**Comment by philvarner** [comment]
OAFeat Part 1 says for both /collection/<missing> and /collection/<missing>/items:

```
If the parameter collectionId does not exist on the server, the status code of the response will be 404 (see [Table 2](https://docs.opengeospatial.org/is/17-069r3/17-069r3.html#status_codes)).
```
