### ISSUE TITLE
Set title, version, description at API top level

### ISSUE THREAD

**Issue by rsmith013** [stac-utils/stac-fastapi#157]
I think these attributes are API level and so should be set in the API layer. It is then the job of the backend to serve data that is compliant with the specified API version.

**Comment by geospatial-jeff** [comment]
We added `title` and `version` in #139 (https://github.com/stac-utils/stac-fastapi/pull/139/files#diff-4f8c5fdc9b3cca78110705589c68a6df26ac7a9d66bd4af3108db5174fdfe49cR63-R64), just need to do the same for `description`.
