### ISSUE TITLE
Add conformance classes to Landing Page

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/stac-fastapi#159]
The LandingPage should include conformance classes to describe the conformance classes, in addition to the conformance endpoint.

In addition, there's currently a single conformance class. I'd recommend using:

```
"conformsTo": [
"https://api.stacspec.org/v1.0.0-beta.1/core",
  "https://api.stacspec.org/v1.0.0-beta.1/item-search",
  "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core",
  "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30",
  "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson"
]
```

Along with adding conformance classes based on what extensions are enabled.

From: https://github.com/radiantearth/stac-api-spec/tree/master/core

> The conformsTo section must provide the capabilities of this service. This is the field that indicates to clients that this is a STAC API and how to access conformance classes, including this one. The relevant conformance URI's are listed in each part of the API specification. If a conformance URI is listed then the service must implement all of the required capabilities.

**Comment by philvarner** [comment]
Does stac-fastapi not implement OAFeat also? if so, it should include https://api.stacspec.org/v1.0.0-beta.2/ogcapi-features
