### ISSUE TITLE
3d bbox query throws 500 server error

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#162]
3d bboxes (where the 3rd and 6th entries are elevation) are valid bbox query parameters. These currently throw a 500 error. 

GET /search?bbox=100.0,0.0,0.0,105.0,1.0,1.0

POST /search with `{ "bbox":[100.0, 0.0, 0.0, 105.0, 1.0, 1.0] }` 

The semantics of a 3d bbox query parameter over 2d bbox data is that the 2d bbox is extended to infinite elevation, so that the elevation is effectively ignored.

**Comment by jonhealy1** [comment]
@philvarner Is this an issue with the pgstac backend?

**Comment by philvarner** [comment]
I think I ran it against both backends (it was a while ago).

**Comment by jonhealy1** [comment]
Oh yea - Jun 21 - I will try both.

**Comment by jonhealy1** [comment]
This works with sqlalchemy after loading the db: http://localhost:8080/search?bbox=-135.75,11.8,0.0,-49.0,51.0,1.0
