### ISSUE TITLE
query bbox with invalid latitudes does not return a 400 error

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#163]
The bbox value `100.0, 1.0, 105.0, 0.0` is invalid, as the latitude values are such that the first is greater than the second. This is allowed for longitudes, as it represents anti-meridian-spanning bboxes, but is invalid for latitude. 

stac-fastapi returns a 200 response for this query parameter, presumably with no matching results, instead of a 400 indicating that the bbox is invalid.

**Comment by geospatial-jeff** [comment]
Good catch, this will require a change to stac-pydantic, I'll open an issue over there.

**Comment by geospatial-jeff** [comment]
We can close this issue once a new stac-pydantic version is released.
