### ISSUE TITLE
migrate to newer version of stac-pydantic

### ISSUE THREAD

**Issue by rsmith013** [stac-utils/stac-fastapi#164]
stac-pydantic 1.3.9 has moved some imports. Validation rules break compatibility with `stac_fastapi.sqlalchemy`. Might need to develop in tandem and pin to a 1.3.10 release of stac-pydantic or something...

**Comment by lossyrob** [comment]
Agree to pinning the stac-pydantic release to avoid upgrade issues...

I'll note here that there is work in progress to make stac-pydantic work with STAC 1.0 here: https://github.com/stac-utils/stac-pydantic/pull/86. Once that is merged, the plan as I understand it is to make a new release of stac-pydantic and use that within stac-fastapi. This, along with the work to move away from Pydantic encoding of responses in #147, will move this project fully to STAC 1.0, and that's when there'll be a new release of stac-fastapi.

During that process we should make sure stac-pydantic is pinned to the proper version.

**Comment by geospatial-jeff** [comment]
Just a note that stac-pydantic 2.0 has been released which migrates to STAC v1.0
