### ISSUE TITLE
pgstac client removes existing links from Collection

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/stac-fastapi#166]
[This line](https://github.com/stac-utils/stac-fastapi/blob/master/stac_fastapi/pgstac/stac_fastapi/pgstac/core.py#L106) overwrites any existing links on the Collection. This e.g. removes the "license" link that may exist for a Collection. This should be changed to extend the list of links with the generated links instead.

**Comment by lossyrob** [comment]
Also happens here: https://github.com/stac-utils/stac-fastapi/blob/master/stac_fastapi/pgstac/stac_fastapi/pgstac/core.py#L143

**Comment by moradology** [comment]
I'm going to try to use the `extra_links` argument to `get_links` to resolve this issue before resorting to list concatenation - it looks like some of those arguments weren't supplied

**Comment by duckontheweb** [comment]
Closed by #282
