### ISSUE TITLE
errors using docker compose commands to start servers

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#170]
Per the instructions, running

```
docker-compose build
docker-compose up
```

does not seem to work. I can connect to the pgstac server on 8082, but not the sqlalchemy one on 8081, and the sqlalchemy server seems to be constantly restarting. 

I see these errors in the startup log:

```
pgstac-loadjoplin_1     | requests.exceptions.ConnectionError: HTTPConnectionPool(host='app-pgstac', port=8082): Max retries exceeded with url: /collections (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f69d91529a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

```
sqlalchemy-migration_1  | requests.exceptions.ConnectionError: HTTPConnectionPool(host='app-sqlalchemy', port=8081): Max retries exceeded with url: /collections (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09e1e4e9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

This is using Docker Desktop for MacOSX.

**Comment by geospatial-jeff** [comment]
Thats strange, I'm also using Docker Desktop for Mac and it works for me.  

```
stac-fastapi-pgstac     | INFO:     172.18.0.1:58884 - "GET /collections HTTP/1.1" 200 OK
stac-fastapi-sqlalchemy | INFO:     172.18.0.1:63570 - "GET /collections HTTP/1.1" 200 OK
```

I'm running with the following versions:
- Docker Desktop 3.3.0
- Docker Engine 20.10.5
- Compose 1.29.0

**Comment by philvarner** [comment]
I'm running Docker Desktop 3.5.1, which is latest.

**Comment by guidorice** [comment]
On `master` (b5b261fac0850d682c13ed2459f10d70d81bbaf6) I get this new error 

```
$ docker-compose build
$ docker-compose up
...
Creating stac-db ... error

ERROR: for stac-db  Cannot create container for service database: Conflict. The container name "/stac-db" is already in use by container "12f2524dc02d66a25bbe84bf4700047d212326add50fd0bdfcc3b9f2d74b84b1". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for database  Cannot create container for service database: Conflict. The container name "/stac-db" is already in use by container "12f2524dc02d66a25bbe84bf4700047d212326add50fd0bdfcc3b9f2d74b84b1". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
```

I am on MacOS w/ Docker 3.5.1

Before trying, I have cleaned my docker environment completely using this script, fwiw:

```shell
#!/usr/bin/env bash

for n in {1..3}; do
    echo wipe $n
    docker system prune --force
    docker image prune --force --all;
done
```

**Comment by kylebarron** [comment]
> ERROR: for stac-db  Cannot create container for service database: Conflict. The container name "/stac-db" is already in use by container "12f2524dc02d66a25bbe84bf4700047d212326add50fd0bdfcc3b9f2d74b84b1". You have to remove (or rename) that container to be able to reuse that name.

Can you try
```
docker stop 12f2524dc02d66a25bbe84bf4700047d212326add50fd0bdfcc3b9f2d74b84b1
docker rm 12f2524dc02d66a25bbe84bf4700047d212326add50fd0bdfcc3b9f2d74b84b1
```

**Comment by guidorice** [comment]
Thanks @kylebarron and @duckontheweb for pointing out I probably had running containers already :) OK so that's my bad sorry for the noise.  However, now I am seeing one of the same error as @philvarner now:

> pgstac-loadjoplin_1     | requests.exceptions.ConnectionError: HTTPConnectionPool(host='app-pgstac', port=8082): Max retries exceeded with url: /collections (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13119159a0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by duckontheweb** [comment]
It's possible this is a race condition where the FastAPI app in the `app-pgstac` service isn't ready by the time the request is made. It looks like the `pgstac-loadjoplin` service has a delay built in here to try to handle this:

https://github.com/stac-utils/stac-fastapi/blob/b5b261fac0850d682c13ed2459f10d70d81bbaf6/docker-compose.yml#L94

Maybe try increasing to `sleep 20` and see if that solves the problem as a workaround?

**Comment by philvarner** [comment]
@duckontheweb Thanks! increasing to 20s worked for me.
