### ISSUE TITLE
pgstac: Return empty item collection instead of error for empty search

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/stac-fastapi#172]
[Here](https://github.com/stac-utils/stac-fastapi/blob/master/stac_fastapi/pgstac/stac_fastapi/pgstac/core.py#L180) pgstac returns a 404 if no items are found. I think a more expected response would be a 200 with an empty ItemCollection, as the search endpoint is found and is working, and the empty search results is a valid result.

**Comment by zstatmanweil** [comment]
@lossyrob: I was about to open an issue for this but found this old one. Looks like you made the change at some point but that branch never made it into a PR. Do you think I can/should open a PR that just isolates the fix for this issue? I don't have much experience contributing to open source so trying to figure out what is appropriate!

**Comment by moradology** [comment]
Yeah, this is one that I could have sworn we'd taken care of but appears to have slipped through the cracks. I think this would be a great contribution and I'd be happy to pick it up myself but if you'd like to take a shot @zstatmanweil, I'd be more than happy to lend a hand when/where useful

**Comment by zstatmanweil** [comment]
Thanks to you both! @moradology, I will give it a shot and let you know if I have questions. I will just implement the change relating to this issue though. I will tag you in the PR when I open it

**Comment by zstatmanweil** [comment]
Thanks for your help with my first PR @lossyrob, @moradology. Looking forward to contributing more! 

We can close this issue now, ya?

**Comment by moradology** [comment]
Absolutely and no problem at all. And in the future, you can replace "This PR addresses issue #172." with "closes #172" and merging the PR will automatically close the referenced issue
