### ISSUE TITLE
Merge PRs by squashing, not by adding all commits

### ISSUE THREAD

**Issue by kylebarron** [stac-utils/stac-fastapi#194]
I'm not sure if this was intentional or not, but when https://github.com/stac-utils/stac-fastapi/pull/147 was merged, it was merged by adding all commits to the `master` branch instead of squashing into a single commit. So there are now many small commits like https://github.com/stac-utils/stac-fastapi/commit/b850bd53aa4ffce434cc220a67db7563a5a2db62 that are now on the `master` branch, which (in my opinion) makes it harder to see the progress of the branch, compared to all changes in a single commit.

It might be ideal to turn off other types of PR merging in the repo's settings?

**Comment by kylebarron** [comment]
These are the options in a repo's settings:
![image](https://user-images.githubusercontent.com/15164633/127033331-1c54764b-2297-4b1f-97b3-87a787e98630.png)

**Comment by kylebarron** [comment]
It looks like at least a few PRs so far have been merged by including all commits instead of by squashing, like https://github.com/stac-utils/stac-fastapi/pull/185.

One other reason I'd suggest to force squashing instead of a merge commit is that `master`'s history is now non-linear, and has many commits that are entirely non-functional.

For example, this commit from #147 is now listed on `master` as being from July 12, while only being merged two days ago. 
![image](https://user-images.githubusercontent.com/15164633/127034929-c630625f-bd01-41ac-a4fe-0c8ec0fc979d.png)

![image](https://user-images.githubusercontent.com/15164633/127034935-b01432ff-1dd6-4772-9b46-158e6e82a856.png)

This makes it harder to understand the history of `master` because that commit _didn't exist on master_ on July 12, so PRs merged between July 12 and 24 show work done before the commit in question.

**Comment by geospatial-jeff** [comment]
I agree squashing is better for merging PRs.  Done.
![image](https://user-images.githubusercontent.com/40916268/127060624-f9651a7f-fb61-4110-b6b5-ca11616dc7d9.png)
