### ISSUE TITLE
Possible breaking change in docker-compose.yml

### ISSUE THREAD

**Issue by jaysnm** [stac-utils/stac-fastapi#205]
Hi

Change of database image from `bitner/pgstac:0.2.4` to `ghcr.io/stac-utils/pgstac:v0.2.8` breaks system spin with 
`ERROR: Head https://ghcr.io/v2/stac-utils/pgstac/manifests/v0.2.8: denied: denied`.
However, reversing image back to `bitner/pgstac:0.2.4` or `bitner/pgstac:0.2.7` (latest) works fine.

**Comment by geospatial-jeff** [comment]
@bitner any ideas here?

**Comment by bitner** [comment]
@geospatial-jeff I'll look

**Comment by jaysnm** [comment]
Turns out to be `ghcr authorization` related problem. Works fine after a `docker logout ghcr.io`. See #208.
