### ISSUE TITLE
Incorrect "conformance" link relation href in Landing Page

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#218]
The Landing Page contains a link relation for `conformance` relation, but this links to the landing page rather than `/conformance`.

This was tested with a local docker-compose instance of stac-fastapi-sqlalchemy.

**Comment by duckontheweb** [comment]
@philvarner I'm not able to replicate this on `main`, it appears the `conformance` link correctly points to `/conformance`. Here are the steps I took:

```console
$ docker-compose up --build app-sqlalchemy database loadjoplin-sqlalchemy
$ curl http://localhost:8081/ | jq '.links[] | select(.rel == "conformance")'
{
  "rel": "conformance",
  "type": "application/json",
  "title": "STAC/WFS3 conformance classes implemented by this server",
  "href": "http://localhost:8081/conformance"
}
```

Do you maybe need to rebuild the images?

**Comment by philvarner** [comment]
I was rebuilding, but I may have been running from someone else's branch that was out of date. Looks fixed now.

**Comment by philvarner** [comment]
CNR
