### ISSUE TITLE
Invalid limit values allowed

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#221]
Unless otherwise advertised in the service-desc (which doesn't currently exist), the valid values for limit are integers 1 to 10000. The following query values return a 200 instead of 400:
 
- GET Search with {'limit': -1} returned status code 200, should be 400
- POST Search with {'limit': -1} returned status code 200, should be 400
- GET Search with {'limit': 0} returned status code 200, should be 400
- POST Search with {'limit': 0} returned status code 200, should be 400
- GET Search with {'limit': 10001} returned status code 200, should be 400
- POST Search with {'limit': 10001} returned status code 200, should be 400

This was tested with a local docker-compose instance of stac-fastapi-sqlalchemy.

**Comment by geospatial-jeff** [comment]
closed with #251, thanks @jonhealy1 !
