### ISSUE TITLE
No public image available

### ISSUE THREAD

**Issue by xenon-dev** [stac-utils/stac-fastapi#228]
It seems that there is no image for stac-fastapi available, not in Docker Hub nor in "quay.io" (RedHat registry).

After building some initial Kubernetes files from the docker files with "Kompose",
we build the image ourselves and put it into the registry attached with our cluster in order to get going.
Could an official image be published to a publicly known repository?
This would probably help others in the future, they could skip the build step and just get the image from an publicly available source.

**Comment by geospatial-jeff** [comment]
@lossyrob does stac-utils org have a docker hub account?

**Comment by lossyrob** [comment]
@geospatial-jeff we've been using GitHub Container Repositories, which are part of the repo's packages and great for publishing containers, e.g. https://github.com/stac-utils/pgstac/pkgs/container/pgstac

**Comment by xenon-dev** [comment]
Thank you very much for clarification @lossyrob!

**Comment by hall-b** [comment]
@lossyrob the link you gave refers to the GitHub Container Repository from PGStac. What about the current project ? I can't find any official public image of stac-fastapi ? If none exists for the moment, are you planning to release one soon ?
