### ISSUE TITLE
Remove tiles extension

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/stac-fastapi#245]
There is currently a tiles extension which allows adding titiler routes to stac-fastapi. My understanding was that this was added as a sort of demo, and that in practice you wouldn't want to couple your STAC API with the titiler implementation - it's better to have those run as separate services, and tiler serving is beyond the scope of this project. Titiler also can cause depenency conflict - e.g. it has a pinned version of fastapi, which overrides a pinned version declared by a stac-fastapi subpackage if that stac-fastapi.extensions extra is installed. 

Based on the conversations I've had with stac-fastapi users that I know of, this shouldn't be a problem; however I'm not sure if someone out there is using this and would hate to see it go. Does anyone depend on this extension? If not, I'll make a PR to drop it.

**Comment by geospatial-jeff** [comment]
> My understanding was that this was added as a sort of demo

This is correct, I added it as a demo for the cloud native geo sprint last fall, agreed it shouldn't be here.  Something like https://github.com/developmentseed/eoAPI is a better pattern.
