### ISSUE TITLE
Incorrect conformance class URI used for oas30

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#255]
The URI used for the OAS conformance class is:
```
http://www.opengis.net/spec/ogcapi-features-1/1.0/req/oas30
```
when it should be:
```
http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30
```

The `req` one is the requirements class, whereas the `conf` one is the conformance class.

**Comment by TomAugspurger** [comment]
@philvarner I'm http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30 gives a 404 Not Found right now. Is that a temporary thing?

I'm looking to harmonize pystac-client (https://github.com/stac-utils/pystac-client/blob/9aebcf4e8c4b0e2cd55243a4cf3d711f045027b4/pystac_client/conformance.py#L43) and stac-fastapi, but I'm not sure which one is the right URL to use.

**Comment by philvarner** [comment]
I'll mention that 404 to the ogcapi team. It'd definitely 'conf'.

**Comment by philvarner** [comment]
See https://github.com/opengeospatial/ogcapi-features/issues/269 and https://github.com/opengeospatial/ogcapi-features/issues/355
