### ISSUE TITLE
sqlalchemy backend does not support non-interval datetime values

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#256]
the datetime parameter should support either single datetime values or intervals. I believe this worked previously, but now the sqlalchemy backend seems to only process intervals correctly. 

All of the stac-api-validator tests with single datetimes fail:

- Search with datetime=2000-02-02T00:00:00+00:00 extracted from an Item returned status code 500
- Search with datetime=1985-04-12T23:20:50.52Z returned status code 500
- Search with datetime=1996-12-19T16:39:57-00:00 returned status code 500
- Search with datetime=1996-12-19T16:39:57+00:00 returned status code 500
- Search with datetime=1996-12-19T16:39:57-08:00 returned status code 500
- Search with datetime=1996-12-19T16:39:57+08:00 returned status code 500
- Search with datetime=1937-01-01T12:00:27.87+01:00 returned status code 500
- Search with datetime=1985-04-12T23:20:50.52Z returned status code 500
- Search with datetime=1937-01-01T12:00:27.8710+01:00 returned status code 500
- Search with datetime=1937-01-01T12:00:27.8+01:00 returned status code 500
- Search with datetime=1937-01-01T12:00:27.8Z returned status code 500
- Search with datetime=2020-07-23T00:00:00.000+03:00 returned status code 500
- Search with datetime=2020-07-23T00:00:00+03:00 returned status code 500
- Search with datetime=1985-04-12t23:20:50.000z returned status code 400
- Search with datetime=2020-07-23T00:00:00Z returned status code 500
- Search with datetime=2020-07-23T00:00:00.0Z returned status code 500
- Search with datetime=2020-07-23T00:00:00.01Z returned status code 500
- Search with datetime=2020-07-23T00:00:00.012Z returned status code 500
- Search with datetime=2020-07-23T00:00:00.0123Z returned status code 500
- Search with datetime=2020-07-23T00:00:00.01234Z returned status code 500
- Search with datetime=2020-07-23T00:00:00.012345Z returned status code 500
- Search with datetime=2020-07-23T00:00:00.0123456Z returned status code 500
- Search with datetime=2020-07-23T00:00:00.01234567Z returned status code 500
- Search with datetime=2020-07-23T00:00:00.012345678Z returned status code 500

Additionally, intervals with an empty string was the start or end datetime return a 400 (per the spec, both empty string and `..` are permissible for open/closed ended:

- Search with datetime=/1985-04-12T23:20:50.52Z returned status code 400
- Search with datetime=1985-04-12T23:20:50.52Z/ returned status code 400

**Comment by jonhealy1** [comment]
@philvarner I was wondering about this recently too. What is the expectation for searching on, for example, "datetime=2000-02-02T00:00:00+00:00"? Should this return all items from 2000-02-02 or just the item with the exact datetime - 2000-02-02T00:00:00+00:00? Would an item with datetime 2000-02-02T00:00:00.00Z be returned? I built a stac api where you could search on the exact date string but then I wondered when it would be useful. Unless you know the exact millisecond you want. It makes more sense to return things from the same day but I don't think that's what you mean.

**Comment by philvarner** [comment]
> What is the expectation for searching on, for example, "datetime=2000-02-02T00:00:00+00:00"? Should this return all items from 2000-02-02 or just the item with the exact datetime - 2000-02-02T00:00:00+00:00? 

exact datetime (or equivalent wrt timezone)

> Would an item with datetime 2000-02-02T00:00:00.00Z be returned? 

yes

> I built a pseudo stac api where you could search on the exact date string but then I wondered when it would be useful. Unless you know the exact millisecond you want. It makes more sense to return things from the same day but I don't think that's what you mean.

Yeah, it's not super-useful, but that's what the OGC API Features - Part 1 spec does, so we reuse.

related to the "on this day" case, one of the other implementations (either cmr-stac or stac-server?) also supports query with a date-only, which has those semantics

**Comment by jonhealy1** [comment]
Thanks for the reponse! It makes a lot more sense now.

**Comment by geospatial-jeff** [comment]
closed with #262
