### ISSUE TITLE
Prevent SSL-termination from breaking links

### ISSUE THREAD

**Issue by McSurf84** [stac-utils/stac-fastapi#261]
I´m using stac-fastapi with pgstac on a kubernetes cluster with ingress (https) and SSL-termination.
So all links in my catalog and collections get the http scheme instead of https and this causes mixed-content errors, e. g. in STAC-Browser.

To prevent this, I´ve added some changes dependent by a environment variable to the baseurl creation in 
- stac_fastapi/pgstac/stac_fastapi/pgstac/models/links.py 
- stac_fastapi/types/stac_fastapi/types/core.py
so all links will be generated with https scheme.

I´d like to discuss if this is a good way or if there is a better solution?.

**Comment by kylebarron** [comment]
https://stackoverflow.com/a/64146281

**Comment by geospatial-jeff** [comment]
closing this as I think it's resolved
