### ISSUE TITLE
Remove default middleware in `stac_fastapi.api.app.StacApi`

### ISSUE THREAD

**Issue by vincentsarago** [stac-utils/stac-fastapi#265]
Having a compression middleware is a nice thing but IMO it shouldn't be included by default. 

https://github.com/stac-utils/stac-fastapi/blob/2347e6b590a589a643ea0cd6655b0244dbc4d48d/stac_fastapi/api/stac_fastapi/api/app.py#L349

My main motivation is that I often build my own custom application (and then choose what middleware to add) (e.g https://github.com/developmentseed/eoAPI/blob/master/src/eoapi/stac/eoapi/stac/app.py#L34-L44)

**Comment by geospatial-jeff** [comment]
closed in #267, thanks @vincentsarago !
