### ISSUE TITLE
GET with cql-text doesn't work for /search endpoint

### ISSUE THREAD

**Issue by drnextgis** [stac-utils/stac-fastapi#279]
I'm trying to translate the following query to its `GET` equivalent:
```
$ curl --request POST \
  --url https://localhost:8080/search \
  --header 'Content-Type: application/json' \
  --data '{"filter":{"eq":[{"property":"title"},"task #42"]}}'
```

According to [this](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/filter#example-1-get-with-cql-text) page it should be something like this but it doesn't work:
```
https://localhost:8080/search?filter=title='task #42'
```

Am I missing something?

**Comment by moradology** [comment]
I tried this and things seem to be working fine.

JSON:
```
curl --request POST \
  --url http://localhost:8082/search \
  --header 'Content-Type: application/json' \
  --data '{"filter":{"eq":[{"property":"title"},"task #42"]}}'
```

Text:
```
curl --request GET --url "localhost:8082/search?filter=title='task #42'"
```

Can you provide more information about what's going wrong?

**Comment by geospatial-jeff** [comment]
Closing for now, please feel free to reopen if this problem resurfaces!
