### ISSUE TITLE
Upgrade pgstac version to v0.3.5 or v0.3.6

### ISSUE THREAD

**Issue by zstatmanweil** [stac-utils/stac-fastapi#283]
There are some key performance improvements and updates in the recent versions of pgstac (e.g., being able to turn off "context") that would be great to use with stac-fastapi. Not sure if there are breaking changes in these new versions of pgstac, or the version pinned can just be upgraded. Thanks!

**Comment by moradology** [comment]
Looks like this one got lost in all the shuffle. 0.4.0 came out a few days ago so hopefully we can just jump to that
