### ISSUE TITLE
Query parameters does not support hyphens

### ISSUE THREAD

**Issue by NicolaiMogensen** [stac-utils/stac-fastapi#285]
Query parameters are defined using `attr` and does to my knowledge not support arguments with hyphens in it. Pydantic operates with something called "aliases" that supports this, but pydantic is currently only used for the database models, and not the query models ( also why not also use pydantic for the query models ). 

This is important because the OGC API Features Part 2 - Coordinate Reference Systems by Reference requires a field called `bbox-crs`, notice the hyphen. Backends wanting to support this query parameter can't currently, without quite a lot of code re-writing. Specifically the SQLalchemy backend does not handle this, and is the only backend i've tested with.

**Comment by AsgerPetersen** [comment]
We fixed this by using properties defined like

```python
from fastapi import Query 

@attr.s
class FilterableRequest:
    # More props
    bbox_crs: Optional[str] = attr.ib(default=Query(default=None, alias="bbox-crs"))
```

**Comment by moradology** [comment]
This looks like the shape of a good solution. I'm going to close this but you should feel free to reopen it if there's something we've missed, @NicolaiMogensen
