### ISSUE TITLE
Search with (valid) open interval times throwing 400s

### ISSUE THREAD

**Issue by moradology** [stac-utils/stac-fastapi#293]
- Search with datetime=/1985-04-12T23:20:50.52Z returned status code 400
- Search with datetime=1985-04-12T23:20:50.52Z/ returned status code 400

**Comment by jonhealy1** [comment]
Shouldn't the datetime open interval look like this datetime="../1985-04-12T23:20:50.52Z" and also datetime="1985-04-12T23:20:50.52Z/.." with the two dots before or after the slash?

**Comment by moradology** [comment]
I've also seen it written exclusively with the `..` before/after. My comment above is merely copy/pasted from the output of the stac-api-validator https://github.com/stac-utils/stac-fastapi/issues/286.

**Comment by moradology** [comment]
This issue is being addressed upstream, here: https://github.com/stac-utils/stac-pydantic/pull/103

**Comment by moradology** [comment]
I believe this should now be fixed with the stac-pydantic relase of 2.0.2 and our use of a wildcard in the minor version here: https://github.com/stac-utils/stac-fastapi/blob/master/stac_fastapi/api/setup.py#L11
