### ISSUE TITLE
Landing page urls are still http when behind a proxy using SSL

### ISSUE THREAD

**Issue by rsmith013** [stac-utils/stac-fastapi#301]
Instances of stac-fastAPI running using HTTP behind a secure proxy still get the base URL with HTTP.

Need a way to force HTTPS URLs when running behind a secure proxy.

**Comment by jonas-eberle** [comment]
Hi @rsmith013, 

I have used the `FORWARDED_ALLOW_IPS` environment variable from uvicorn: https://www.uvicorn.org/settings/#http
> --forwarded-allow-ips Comma separated list of IPs to trust with proxy headers. Defaults to the $FORWARDED_ALLOW_IPS environment variable if available, or '127.0.0.1'. A wildcard '*' means always trust.


Don't know if there is a better way. At least it worked for me. 

Best
Jonas

**Comment by McSurf84** [comment]
Had the same issue (https://github.com/stac-utils/stac-fastapi/issues/261#issuecomment-940925210) and FORWARDED_ALLOW_IPS solved it, too.

**Comment by rsmith013** [comment]
that has worked. Thanks
