### ISSUE TITLE
Datetime no longer a parameter option in GET /search

### ISSUE THREAD

**Issue by zstatmanweil** [stac-utils/stac-fastapi#315]
In a recent [PR](https://github.com/stac-utils/stac-fastapi/pull/308/files),`Dict` was added as a type option for datetime in `BaseSearchGetRequest` 
https://github.com/stac-utils/stac-fastapi/blob/2f8e96bbdbad588e3b5df7f28dda5bd737228fcc/stac_fastapi/types/stac_fastapi/types/search.py#L76

After this change, for some reason `datetime` is no longer registering as a parameter in the GET /search endpoint for sqlalchemy or pgstac backend. You can confirm this by running it locally, and looking at the `/docs` or `/api` pages.  Alternatively, you can run a GET request on this URL and see that the item returned should actually be filtered out based on the datetime:

```http://0.0.0.0:8082/search?collections=joplin&ids=f2cca2a3-288b-4518-8a3e-a4492bb60b08&datetime=2021-02-02T00:00:00Z/2022-02-02T00:00:00Z```

I removed the `Dict` option and datetime reappeared as a parameter. 

Since this was made as part of the pgstac upgrade to 0.4.0, I assume it has something to do with that, but downstream all the functions expect a `str` or `datetime` so I haven't been able to figure it out. I see that cql2-json can take a dictionary for datetime within the filter parameter, but since the `datetime` parameter is not available in cql2-json, I don't think that applies here.

**Comment by zstatmanweil** [comment]
hey @bitner , why was `Dict` added as an option to the datetime parameter in GET /search? I am happy to add a PR to fix this issue and add tests etc. but I didn't want to just delete that without understanding!

**Comment by bitner** [comment]
Hey @zstatmanweil off the top of my head, I'm not entirely sure. Definitely open to a PR with Tests!

There are definitely going to be quite a few changes in the area coming up as I'm working on CQL2-Text support. From a backend perspective, pgstac only takes cql-json (which should be considered deprecated as new work will only focus on cql2) or cql2-json, so the GET's job is just to convert the GET parameters into CQL-JSON / CQL2-JSON. I'm currently adding at cql2-json backend to [pygeofilter](https://github.com/geopython/pygeofilter/pull/41) and the plan is that anything other than CQL2-JSON in stac-fastapi-pgstac will get translated by pygeofilter into cql2-json.

**Comment by zstatmanweil** [comment]
Thanks, @bitner. All makes sense! I will open a PR for this with some additional tests to catch this issue. More tests should also help with this big overhaul - looking forward to seeing it
