### ISSUE TITLE
Nosql backend

### ISSUE THREAD

**Issue by jonhealy1** [stac-utils/stac-fastapi#316]
I am building a mongo backend for stac-fastapi here: https://github.com/jonhealy1/stac-fastapi-mongo
It still needs some work - transactions and core run and tests pass but other extensions need work, tlc. The way mongodb is setup could probably be improved if anyone knows anything about it. There are probably other things that need improvement or work too. I am no mongo expert.

**Comment by jonhealy1** [comment]
I am creating an elasticsearch backend now. Some of the tests fail so I'm skipping them but I can't figure out why many are failing. There's a point intersection test for example that works fine when I repeat the steps in postman. I'm just starting to learn elasticsearch so there is probably a lot of work here optimizing queries etc. https://github.com/jonhealy1/stac-fastapi-mongo-elasticsearch/tree/elastic_search

**Comment by jonhealy1** [comment]
If anyone is interested there is an elasticsearch backend in development here: https://github.com/stac-utils/stac-fastapi-elasticsearch
A mongo backend is here: https://github.com/jonhealy1/stac-fastapi-mongo

**Comment by geospatial-jeff** [comment]
Closing this issue as we are moving backends out of this repo, ref #432
