### ISSUE TITLE
search parameter `ids` does not filter (pgstac backend)

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#333]
Steps:
1. Run pgstac backend locally using docker
2. retrieve`http://0.0.0.0:8082/search?ids=fe916452-ba6f-4631-9154-c249924a122d`

Expected behavior:
all result Items that have the id fe916452-ba6f-4631-9154-c249924a122d

Actual:
`ids` parameter seems to have no effect on results

**Comment by drnextgis** [comment]
Workaround is to enable FilterExtension: https://github.com/stac-utils/stac-fastapi/issues/335#issuecomment-1024628747

**Comment by bitner** [comment]
Closing this issue as a duplicate (or at least subsumed by) of #335
