### ISSUE TITLE
Update stac-fastapi.pgstac uvicorn version dependency to at least 0.16 to eliminate security issue with websockets

### ISSUE THREAD

**Issue by jclark-indigoag** [stac-utils/stac-fastapi#342]
Super minor....

stac-fastapi.pgstac has a uvicorn version >=0.12, <=0.14 dependency here: 
https://github.com/stac-utils/stac-fastapi/blob/5dc8e0eb63d9cc07663968ed5ed9505e753bf298/stac_fastapi/pgstac/setup.py#L33

these versions of uvicorn have a websockets dependency that looks like: 
```yaml
websockets = {version = ">=8.0.0,<9.0.0"
```

and websockets versions <9.1 have a security vulnerability which is triggering a dependabot security alert: 

<img width="919" alt="Screen Shot 2022-01-28 at 1 01 42 PM" src="https://user-images.githubusercontent.com/96131149/151598341-cf0b96f6-49e1-4a63-a30e-1665b4d141f3.png">

Updating uvicorn to >=[0.16](https://github.com/encode/uvicorn/releases/tag/0.16.0) will update websockets to >=0.10 and eliminate this security issue. 

edit: also in stac-fastapi.sqlalchemy here:
https://github.com/stac-utils/stac-fastapi/blob/5dc8e0eb63d9cc07663968ed5ed9505e753bf298/stac_fastapi/sqlalchemy/setup.py#L33

**Comment by jclark-indigoag** [comment]
If this is accepted, I'm happy to submit a PR for this lil' change

**Comment by geospatial-jeff** [comment]
@jclark-indigoag a PR would be much appreciated, thanks for catching this!
