### ISSUE TITLE
collections/{collection_id}/items and collections/{collection_id}/items/{item_id} return incorrect results

### ISSUE THREAD

**Issue by davidraleigh** [stac-utils/stac-fastapi#345]
## Summary
Seeing incorrect results for collections/{collection_id}/items and collections/{collection_id}/items/{item_id}. Maybe this is a pgstac error?

## To Reproduce
add lines to create empty-collection at end of `ingest_joplin_data` function (right below line [44](https://github.com/stac-utils/stac-fastapi/blob/2.3.0/scripts/ingest_joplin.py#L45)):
```python
    collection["id"] = "empty-collection"
    post_or_put(urljoin(app_host, "/collections"), collection)
```

run pgstac app
```
git checkout 2.3.0
docker-compose build
docker-compose -d app-pgstac
python scripts/ingest_joplin.py http://localhost:8082
```

## Expected

- http://0.0.0.0:8082/collections/empty-collection/items
should return context { limit: 10, returned: 0}

- http://0.0.0.0:8082/collections/empty-collection/items/fe916452-ba6f-4631-9154-c249924a122d
should return return 404

- http://0.0.0.0:8082/collections/joplin/items/f7f164c9-cfdf-436d-a3f0-69864c38ba2a
should return item for id f7f164c9-cfdf-436d-a3f0-69864c38ba2a

## Actual results
- http://0.0.0.0:8082/collections/empty-collection/items
returns first 10 items for joplin

- http://0.0.0.0:8082/collections/empty-collection/items/fe916452-ba6f-4631-9154-c249924a122d
returns joplin item fe916452-ba6f-4631-9154-c249924a122d

- http://0.0.0.0:8082/collections/joplin/items/f7f164c9-cfdf-436d-a3f0-69864c38ba2a
returns joplin item fe916452-ba6f-4631-9154-c249924a122d

**Comment by vincentsarago** [comment]
@davidraleigh can you try with pgstac 0.4.5 by updating https://github.com/stac-utils/stac-fastapi/blob/master/docker-compose.yml#L68

**Comment by bitner** [comment]
PR bumping pgstac version that should fix this incoming.....

**Comment by davidraleigh** [comment]
Thank you for the heads up on 0.4.5.

It solves my issue for these two routes
- http://0.0.0.0:8000/collections/empty-collection/items
- http://0.0.0.0:8000/collections/joplin/items/f7f164c9-cfdf-436d-a3f0-69864c38ba2a

But this route is still returning results for joplin when empty-collection is empty
 - http://0.0.0.0:8000/collections/empty-collection/items/fe916452-ba6f-4631-9154-c249924a122d

**Comment by davidraleigh** [comment]
let me know if you want me to close this issue, change this issue to address the lack of a 404 returned for an empty collection with a joplin stac id, or open a new issue for it.
