### ISSUE TITLE
Geospatial queries in pgstac

### ISSUE THREAD

**Issue by jonhealy1** [stac-utils/stac-fastapi#348]
I'm testing different databases with stac-fasapi and I noticed that geospatial queries in pgstac seem to not be working. I have tested bbox and point intersect queries. No matter what location I use to query, I seem to get the same 10 default results back from the api. Also, if I add a collections parameter it will return the same results even if I spell the name wrong. I'm adding a screenshot where you can see that the result should not be returned based on my query:

<img width="902" alt="Screen Shot 2022-02-17 at 4 10 00 AM" src="https://user-images.githubusercontent.com/19381236/154479503-11694b5e-3700-496b-b36e-aee0f278e158.png">

**Comment by jonhealy1** [comment]
Maybe this is fixed in a new pgstac version?

**Comment by jonhealy1** [comment]
This seems to be working now with pgstac:v0.4.5

Maybe a real issue is how this behaviour passed testing? We may need better tests I think. The tests are sort of designed to be successful I think with usually only loading one item and one collection.

**Comment by kylebarron** [comment]
I think this might be the same as https://github.com/stac-utils/stac-fastapi/issues/335

**Comment by jonhealy1** [comment]
@kylebarron true thanks
