### ISSUE TITLE
How is /collections/{cid}/bulk_items different from POST of ItemCollection to /collections/{cid}/items?

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#354]
Per the Transactions Extension, the /collections/{cid}/items should accept either an Item or an ItemCollection. The Bulk Items endpoint seems to do this same thing, but with non-standard request JSON body that uses `items` instead of `features` as the attribute with the Item entities in it. Why is that?

/collections/{cid}/items also appears not to accept ItemCollection in my testing.

**Comment by geospatial-jeff** [comment]
> /collections/{cid}/items also appears not to accept ItemCollection in my testing.

This is true.  As mentioned in #196 I'm in favor of removing bulk transactions in favor of the `ItemCollection` approach.

**Comment by philvarner** [comment]
We should maintain the BulkTransactionsClient as a concept, through maybe change the signature of:

```def bulk_item_insert(self, items: Items, **kwargs) -> str```

to

```def bulk_item_insert(self, item_collection: ItemCollection, **kwargs) -> str```

or

```def bulk_item_insert(self, items: [Item], **kwargs) -> str```

to still allow bulk inserts to the datastore, since PG and ES both support that and it makes insert quite a lot faster by amortizing the connection overhead.

**Comment by philvarner** [comment]
This is probably covered in https://github.com/stac-utils/stac-fastapi/issues/362
