### ISSUE TITLE
SQLAlchemy backend bulk item insert fails 

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#356]
https://github.com/stac-utils/stac-fastapi/blob/79c0cee7795b95a9ffc5f350c62d4bf69fcc2875/stac_fastapi/sqlalchemy/stac_fastapi/sqlalchemy/transactions.py#L154

I'm not sure what the error is going to be here, because I found this with some derived code that failed in an arbitrarily different way. 

The problem is that `items` is an instance of `Items`, and using this in a list comprehension will iterate over the (string) keys in the `items` dict<string,Any> attribute of Items per it's implementation of `iter`, rather than each Item itself (the values of the dict) as this code expects.

I fixed this in my code with:

```
 processed_items = [self._preprocess_item(item, base_url) for item in items.items.values()]
```

**Comment by geospatial-jeff** [comment]
Closed with #358.  BTW @philvarner I gave you write access as requested in that PR.
