### ISSUE TITLE
In landing page, POST /search link advertises type as application/json instead of application/geo+json

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#357]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/124996/155593073-fdc2d849-811f-4dc9-82e0-3df8a86fa4d7.png">

**Comment by NFuture** [comment]
I am new to opensource but I have learned python and other languages. How can I contribute

**Comment by NFuture** [comment]
cant find where the stac_pydantic is located at to see the LandingPage which the response model which is declared in the api/app.py file

**Comment by philvarner** [comment]
@NFuture look at the LandingPageMixin class
