### ISSUE TITLE
Error response invalid

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/stac-fastapi#360]
Errors in stac-fastapi return as follows: `{ "detail": "Must provide API key or Bearer token to access this route." }`

The API spec says that in case of an error the response should look as follows:
![grafik](https://user-images.githubusercontent.com/8262166/155853670-b1958e4d-8e6b-499e-8e4f-f6c33ef7a134.png)

So stac-fastapi should return something like `{"code": "Unauthorized", "description": "Must provide API key or Bearer token to access this route."}`

**Comment by philvarner** [comment]
This brings up a good question -- what is supposed to be in the `code` field? I don't have a good answer for this.

I had assumed this would be something like a unique identifier for the specific type of error that occurred (e.g., ORA-00001 from <https://docs.oracle.com/database/121/DRDAS/error_code.htm#DRDAS513>). In your example, I'm not sure how "Unauthorized" would be a "code", and it's redundant with the status code that's returned from the server, though maybe that's what "code" is supposed to mean?

**Comment by geospatial-jeff** [comment]
Makes sense to me.  This behavior is coming from [here](https://github.com/stac-utils/stac-fastapi/blob/master/stac_fastapi/api/stac_fastapi/api/errors.py#L46) and [here](https://github.com/stac-utils/stac-fastapi/blob/master/stac_fastapi/api/stac_fastapi/api/errors.py#L71-L74).

**Comment by captaincoordinates** [comment]
@m-mohr could you please clarify where exactly this behaviour is described in the spec?

**Comment by captaincoordinates** [comment]
@m-mohr I would like to see the wider context and see if there is any written explanation to accompany what is shown in the screenshot. I believe this approach is poorly suited to validation errors, which were affected in stac-fastapi by this change, and I want to see if the documentation mentions anything about validation.

**Comment by captaincoordinates** [comment]
@m-mohr thanks for the reference. I'll do some more digging as it seems strange that the spec only allows for a single error response model to cover all scenarios. The previous (non-spec-compliant) stac-fastapi approach for reporting validation errors was more useful as the JSON clearly identified which request field(s) were failing validation, and this information could be used by a client. This change concatenates all validation errors in a single string and is now harder to parse. It removes a machine-readable response and replaces it with a human-readable response, which seems like the wrong direction for an API.

**Comment by m-mohr** [comment]
You can extend it and add additional fields if you want... maybe open a new PR for the (unintended?) side effect?
