### ISSUE TITLE
Fix logging in exception handlers

### ISSUE THREAD

**Issue by geospatial-jeff** [stac-utils/stac-fastapi#364]
The `exc_info=True` parameter in the exception handlers doesn't actually do anything because the log statement isn't within a `except` block.  It should either be removed or updated to explicitly pass in exception traceback so it is logged:

```python

exc = Exception
logger.error(
    "My error message",
    exc_info=(type(exc), exc, exc.__traceback__)
)
```

Logging every exception that triggers a handler might be overkill, we may just want to log traceback on 5XX responses?

https://github.com/stac-utils/stac-fastapi/blob/master/stac_fastapi/api/stac_fastapi/api/errors.py#L45

**Comment by gadomski** [comment]
So I _think_ this is a non-issue, but it's a little hard to be sure. I checked the handling of (e.g.) a 404 error, and inspected the value of `exc` here: https://github.com/stac-utils/stac-fastapi/blob/6db83a9c05d200d43e83c19a585fcf7f0d9e6396/stac_fastapi/api/stac_fastapi/api/errors.py#L57-L63

```python
>>> type(exc)
<class 'stac_fastapi.types.errors.NotFoundError'>
>>> isinstance(exc, Exception)
True
```

According to the docs on `exc_info`, if it is an exception tuple OR an exception instance, `exc` is used: https://docs.python.org/3/library/logging.html#logging.Logger.debug. So I think we're good? @geospatial-jeff can you re-open if my understanding is incorrect?
