### ISSUE TITLE
Ambigous datetime values are accepted but should be rejected

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#365]
These two datetime values are accepted for query, but are not valid RFC 3339 datetimes, and should be rejected with a 400.

- Search with datetime=1937-01-01T12:00:27.87+0100 returned status code 200 instead of 400 -- no colon between hour and minute in tz
- Search with datetime=1985-12-12T23:20:50.52 returned status code 200 instead of 400 -- no timezone

**Comment by geospatial-jeff** [comment]
Closed with #368
