### ISSUE TITLE
Update stac-api-spec version to 1.0.0-rc.1 and add collections conformance class.

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#366]
1. spec can be update from 1.0.0-beta.4 to 1.0.0-rc.1. There were no substantive changes in beta.5 and rc.1 that require code changes (apart from the handful of issues that were previously out of compliance with the spec ([labeled with spec](https://github.com/stac-utils/stac-fastapi/labels/spec))
2. https://api.stacspec.org/v1.0.0-rc.1/collections can be added as a conformance class, as this is a subset of the already-implmented `STAC API - Features` conformance class.

**Comment by geospatial-jeff** [comment]
Closed with #383
