### ISSUE TITLE
Pinned pgstac dependencies?

### ISSUE THREAD

**Issue by rowanwins** [stac-utils/stac-fastapi#369]
Hi there,
Thanks for a great set of libraries -so helpful!

One thing I encountered in getting things running locally using Docker was that some of my searches weren't working as expected - in trawling through tickets I saw there had been some recent improvements upstream in pgstac and the pypgstac dependencies. I noticed they were pinned in a few spots. 

`docker-compose.yaml`
https://github.com/stac-utils/stac-fastapi/blob/6c22bad84422151ed2ddfe53dd5242f7f83772d3/docker-compose.yml#L68

`stac_fastapi/pgstac/setup.py`
https://github.com/stac-utils/stac-fastapi/blob/6c22bad84422151ed2ddfe53dd5242f7f83772d3/stac_fastapi/pgstac/setup.py#L28

Updating these to the latest resolved my issues so I was wondering if there was a reason they should be pinned or if you'd be happy to accept a PR pointing to the latest versions, or with the pin removed?

Cheers
Rowan

**Comment by duckontheweb** [comment]
This issue is now tracked by stac-utils/stac-fastapi-pgstac#5
