### ISSUE TITLE
Dockerfile improvements, and and deployable version (comments and questions)

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#379]
I've made some improvements to the Dockerfile used for development in stac-fastapi-elasticsearch https://github.com/stac-utils/stac-fastapi-elasticsearch/blob/main/Dockerfile.dev

and created one that generates a deployable image https://github.com/stac-utils/stac-fastapi-elasticsearch/blob/main/Dockerfile.deploy

I can port these changes to here if desired.

A few of the concerns I had about the existing Dockerfile are:

I'm not sure why it uses a 2-phase build with no directives in the first phase?

```
FROM python:3.8-slim as base

FROM base as builder
```

I don't think we have any requirements that need building from source or need git:

```
# Any python libraries that require system libraries to be installed will likely
# need the following packages in order to build
RUN apt-get update && apt-get install -y build-essential git
```

This isn't used anywhere in our code, and I couldn't find any tools that require it:

```
ARG install_dev_dependencies=true
```

So it creates an /install dir, but then never uses it?

```
ENV PATH=$PATH:/install/bin

RUN mkdir -p /install && \
```

**Comment by geospatial-jeff** [comment]
Leaving this open for now, I'm hoping that #432 resolves this.

**Comment by duckontheweb** [comment]
This is being tracked for the PgSTAC backend by stac-utils/stac-fastapi-pgstac#10.
