### ISSUE TITLE
/collections/{collectionId}/items endpoint only does not apply bbox or datetime parameters to results

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#380]
It looks like of the `limit` parameter is the only parameter that gets applied to the `/collections/{collectionId}/items` endpoint. 

This would **probably** be acceptable if the server only advertised the **STAC API - Features** conformance class (https://api.stacspec.org/v1.0.0-beta.4/ogcapi-features"), as the spec says (https://github.com/radiantearth/stac-api-spec/tree/master/ogcapi-features):

```
Implementations may optionally provide support for the full superset of STAC API query parameters to the /collections/{collectionId}/items endpoint, where the collection ID in the path is equivalent to providing that single value in the collections query parameter in STAC API.
```

(It's a separate issue as to if this should require the same as OAFeat, but that's TBD)

However, the server advertises the OAFeat class `http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core`, which means that 
`bbox` and `datetime` must also be accepted as filtering parameters.

**Comment by m-mohr** [comment]
Support for bbox and datetime would be a nice addition, indeed.

**Comment by carderne** [comment]
@philvarner @m-mohr might be worth having your input on this PR: #477

**Comment by Mec-iS** [comment]
can this be closed?

**Comment by vincentsarago** [comment]
yes, we can now extend the `/items` endpoint with bbox, datetime and other parameters
