### ISSUE TITLE
Transactions Extension: PUT endpoint is incorrect, should be /collections/{c_id}/items/{i_id}

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#385]
Currently, the PUT endpoint is `/collections/{c_id}/items`. However, according to the Txn Ext spec, this is supposed to be `/collections/{c_id}/items/{i_id}`

This may be a bit challenging to implement, as there are no endpoints currently that take both a body and path or query parameters, so `_create_endpoint` may need a bit of refactoring to allow both.

**Comment by duckontheweb** [comment]
@philvarner I'm working on this as part of the PR to address #406 and #384. Should `PUT /collections` also be changed to `PUT /collections/{c_id}`?
