### ISSUE TITLE
Should docker-compose default RELOAD to true?

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#386]
Setting RELOAD to true when using docker-compose will allow the app to hot reload.  This is the most common scenario when doing development. Should this be set to true by default? Relatedly, this isn't documented anywhere, so if it does stay as false, it should be documented in CONTRIBUTING.

**Comment by geospatial-jeff** [comment]
I think it should be enabled, the docker-compose stack is mostly there for local development so it seems like a sensible default.

**Comment by philvarner** [comment]
I'll create a PR for it and document the behavior.
