### ISSUE TITLE
Base url as parameter

### ISSUE THREAD

**Issue by glaroc** [stac-utils/stac-fastapi#404]
Hi, we are in a situation where we would like to run the stac-fastapi in a virtual machine behind a proxy server. In other words, the uri in the request parameters that the app sees are not the uri that the end user sees, so the urls shown in the catalogue are wrong. Is there a way to set the base url from an environmental variable or through a parameter ? We are currently deploying from docker-compose.

**Comment by glaroc** [comment]
If anyone is facing the same issue, we dealt with it through our nginx reverse proxy. 

````
   location /stac-fast-api/ {
        proxy_http_version  1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host $host/stac-fast-api;
        proxy_pass http://stac-api-app:8082/;
    }
````

Importantly, the following environment variable must be site, here in the docker-compose file

**Comment by vincentsarago** [comment]
maybe this can help https://github.com/developmentseed/titiler/discussions/345#discussioncomment-1636050

**Comment by glaroc** [comment]
@vincentsarago this is the same solution we ended up using. Thank you.

**Comment by gnosys-ccoupal** [comment]
I'm having a similar issue trying to access stac-fastapi behind AWS API Gateway. I can get through, but all the links are shown as the EC2 instance DNS name, not the advertised API gateway domain name. My docker container has the environment variable `FORWARDED_ALLOW_IPS=*`, and I added proxy_headers=True to uvicorn.run (required?) as below:

```
        uvicorn.run(
            "stac_fastapi.sqlalchemy.app:app",
            host=settings.app_host,
            port=settings.app_port,
            log_level="info",
            reload=settings.reload,
            proxy_headers=True,
        )
```

Any ideas?

**Comment by geospatial-jeff** [comment]
#415 added support for forwarding headers
