### ISSUE TITLE
Transaction Extension: purpose of the collection_id path parameter

### ISSUE THREAD

**Issue by drnextgis** [stac-utils/stac-fastapi#406]
What is the purpose of `{collection_id}` path parameter? It seems we can put an arbitrary value there and stac-fastapi will take collection name from the body.

![image](https://user-images.githubusercontent.com/866124/170303431-743f0b4d-bae7-4e81-bd4c-331b8fe7d7ca.png)

Since there is no way to specify `collection_id` via UI it uses `{collection_id}` as it is :man_shrugging:

**Comment by duckontheweb** [comment]
The STAC Spec also requires that a link with a `rel` type of `collection` be present if the `collection` property is present. This means that if you are using something like `pystac.Item.validate` to validate Items prior to insertion you have to add that link, even though it is going to be replaced by the backend anyway.

It seems like the desired behavior here would be:
1. Use the `collection_id` path parameter from the request if there is no `collection` property in the body *or* if that property is present and matches the path parameter
2. Raise an exception if the `collection` property is present and does not match the path parameter.
