### ISSUE TITLE
how to run DB migrations for pgstac? 

### ISSUE THREAD

**Issue by gnosys-ccoupal** [stac-utils/stac-fastapi#413]
I managed to get the alchemy back end running against an aurora postgres database. I wanted to move back to pgstac (it seems more active), and in doing so, I noticed there doesn't appear to be any db migrations to install the required db functions (e.g. get_collections()). My assumption here is that the db image comes with the required functions.. but curious if there is some script that can be run to create them in a new database?

**Comment by duckontheweb** [comment]
Those migrations come with the `pypgstac` Python package that is part of the `pgstac` repo. You can install that Python package according to the instructions [here](https://github.com/stac-utils/pgstac#pypgstac) and then run the migrations as documented in the [Migrations section](https://github.com/stac-utils/pgstac#migrations). You can pass a connection string to the `pypgstac migrate` command using the `--dsn` option as follows:

```console
$ pypgstac migrate --dsn postgres://my_user:my_password@hostname:5432/database_name
```
