### ISSUE TITLE
Support Forwarded and X-Forwarded-* HTTP headers

### ISSUE THREAD

**Issue by captaincoordinates** [stac-utils/stac-fastapi#414]
Both pgstac and sqlalchemy applications are ignorant of Forwarded and X-Forwarded-* HTTP headers and construct all URLs relative to the URL via which the request was received. This is a problem for deployments behind a load balancer or other proxy as the URL to hit the public endpoint may differ from the URL of the request forwarded from the load balancer / proxy to stac-fastapi.

For example: https:// is sometimes switched to http:// when a load balancer forwards a request if the load balancer terminates SSL. As a result URLs in links returned by stac-fastapi will incorrectly specify the http protocol. This might not always be a problem, as a load balancer may redirect http:// to https:// via a 301 or 302 response, but not all clients follow 301 / 302 redirects. This has been observed causing problems in titiler when talking to stac-fastapi behind a load balancer. Additionally a load balancer or reverse proxy might forward requests to proxied applications using a non-standard internal port, and this port should not be referenced in returned links.

FastAPI supports a [root_path](https://fastapi.tiangolo.com/advanced/behind-a-proxy/) parameter to address a problem that is similar but different. root_path is appended by FastAPI to `f"{protocol}://{domain}[:{port}]/"` and therefore cannot be used to change protocol or port in URLs.

**Comment by gnosys-ccoupal** [comment]
I'm not positive, but this seems similar to https://github.com/stac-utils/stac-fastapi/issues/404

For me, I'm not using nginx so the solution provided doesn't help me much. I'm looking at either an ECS or API Gateway based solution.

**Comment by captaincoordinates** [comment]
@gnosys-ccoupal I think API Gateway should provide forwarding headers by default, and if it doesn't it certainly should be configurable, as this is expected proxy behaviour. I've used this approach in ECS with an ALB and it worked as expected.
