### ISSUE TITLE
Publish a new release?

### ISSUE THREAD

**Issue by jonhealy1** [stac-utils/stac-fastapi#422]
There have been A LOT of changes since the last release.

**Comment by geospatial-jeff** [comment]
Thanks @jonhealy1 I'll be releasing 2.4.0 tomorrow once #441 is finished!

**Comment by jonhealy1** [comment]
Yes! Thanks. Changes look great

**Comment by geospatial-jeff** [comment]
https://github.com/stac-utils/stac-fastapi/releases/tag/2.4.0

**Comment by vincentsarago** [comment]
🙏 Thanks @geospatial-jeff
