### ISSUE TITLE
Support enabling CORS with the use of an Environment Variable

### ISSUE THREAD

**Issue by alexgleith** [stac-utils/stac-fastapi#430]
Hey folks, love your work!

It would be great if we can do a few more common configuration things without needing to build a custom Docker image.

One important example is CORS. I know we can install the CORS Middleware for FastAPI, but what if we could run the Docker image with `ENABLE_CORS=true` or `CORS_DOMAINS="*"`  and it _just worked_. That would be nice, right!

Thoughts?

**Comment by drnextgis** [comment]
https://github.com/stac-utils/stac-fastapi/pull/341

**Comment by alexgleith** [comment]
Duplicate, whoops. I'll comment on the other one.
