### ISSUE TITLE
How do I set up Fast API to write URIs with HTTPS instead of HTTP?

### ISSUE THREAD

**Issue by alexgleith** [stac-utils/stac-fastapi#431]
My self link and all the other links to the API are currently:

```
{
"rel": "self",
"type": "application/json",
"href": "http://example.com/"
},
```

But I'm hosting behind a nginx proxy, which is handling HTTPS. How can I tell this app what URIs to write?

**Comment by alexgleith** [comment]
Oddly, the swagger docs show the correct URLs:

```
curl -X 'GET' \
  'https://stac.dev.aodn.org.au/collections/test/items/1' \
  -H 'accept: application/json'
  ```

**Comment by alexgleith** [comment]
Other places do not

![image](https://user-images.githubusercontent.com/3445853/181176320-56a50136-a22e-43f5-9e83-deb1689e0035.png)

**Comment by vincentsarago** [comment]
@alexgleith can you check https://github.com/developmentseed/titiler/discussions/345#discussioncomment-1636050
to me it seems that's a starlette/nginx configuration issue!

**Comment by alexgleith** [comment]
Yeah, ok. It's probably nginx config.

I'm using [magic Docker Compose](https://github.com/aodn/aodn-stac/blob/main/docker-compose.yml) `nginx-proxy` to set it up and I guess I need to do a bit of custom nginx config.

Really didn't want to dive into this too much for this test server!

**Comment by alexgleith** [comment]
Ok, so looking deeper in the the nginx-proxy config, this is in there already:

```
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
proxy_set_header X-Original-URI $request_uri;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
```

This should be all that is required, right?

**Comment by alexgleith** [comment]
Aha, I found it in the uvicorn docs, here: https://www.uvicorn.org/deployment/#running-from-the-command-line

You need to set `--forwarded-allow-ips='*'` for something proxied behind nginx. So fixed!!
