### ISSUE TITLE
 Swagger doesn't mark collection's type field as required

### ISSUE THREAD

**Issue by drnextgis** [stac-utils/stac-fastapi#460]
According to the collection's [specification](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#collection-fields) `type` field is **required**. But if we enable `ENABLE_RESPONSE_MODELS=true` Swagger doesn't mark this field as required:
![image](https://user-images.githubusercontent.com/866124/191260130-8a37348d-3b94-4a0a-9b48-fa2e55a031ef.png)

**Comment by vincentsarago** [comment]
This is now fixed https://github.com/stac-utils/stac-fastapi/blob/69dcee0f23d4a20db2d8e30a9300c0ec35b35b9b/stac_fastapi/api/stac_fastapi/api/app.py#L318-L325


<img width="1234" alt="Screenshot 2024-07-24 at 10 51 16 AM" src="https://github.com/user-attachments/assets/945c31ea-c6c4-439d-917c-9ebd41776884">
