### ISSUE TITLE
GET /search with bbox and intersects returned status code 200

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#463]
Per the Item Search spec, /search called with a bbox and intersects should return a 400. When running against Planetary Computer, this returns a 200.

**Comment by gadomski** [comment]
@philvarner I think this is fixed, can you confirm from your end? Here's how I checked:

```shell
$ curl -i --json @query.json https://planetarycomputer.microsoft.com/api/stac/v1/search
HTTP/2 400 
content-length: 124
content-type: text/plain; charset=utf-8
strict-transport-security: max-age=15724800; includeSubDomains
access-control-allow-origin: *
access-control-allow-credentials: true
x-cache: CONFIG_NOCACHE
x-azure-ref: 0UNLaYwAAAADvTHj17Z8kSZvAjSBV+G7DV1NURURHRTA4MTUAOTI3YWJmYTYtMTlmNi00YWYxLWEwOWQtYzk1OWQ5YTFlNjQ0
date: Wed, 01 Feb 2023 20:57:52 GMT

1 validation error for Request
body -> intersects
  intersects and bbox parameters are mutually exclusive (type=value_error)
```

`query.json`:

```json
{
    "bbox": [
        -180,
        -90,
        180,
        90
    ],
    "intersects": {
        "type": "Point",
        "coordinates": [
            -105.1019,
            40.1672
        ]
    },
    "limit": 1,
    "collections": [
        "aster-l1t"
    ]
}
```

**Comment by philvarner** [comment]
Looks good, that's the expected 400. One other issue that should be filed is that the response to that should be a JSON object matching this https://github.com/radiantearth/stac-api-spec/blob/main/core/commons.yaml#L15 rather than plaintext

**Comment by gadomski** [comment]
With latest **main** of **stac-fastapi**, the response is a JSON object:

```shell
$ curl -si --json @query.json http://localhost:8080/search
HTTP/1.1 400 Bad Request
date: Thu, 02 Feb 2023 14:32:46 GMT
server: uvicorn
content-length: 176
content-type: application/json

{"code":"RequestValidationError","description":"1 validation error for Request\nbody -> intersects\n  intersects and bbox parameters are mutually exclusive (type=value_error)"}
```

The Planetary Computer API is pinned to 25879afe94296eb82b94b523bfa2871b686e035a of this repo, which also has the correct JSON response. It looks like the PC is opting to return plain text responses, so I've opened an issue over there to capture: https://github.com/microsoft/planetary-computer-apis/issues/151. Closing this one as compelte.
