### ISSUE TITLE
Add numberReturned and numberMatched fields to ItemCollection responses

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#478]
stac-fastapi advertises OAFeat as a conformance class, but doesn't include `numberReturned` or `numberMatched` in the .../items endpoint response. These are optional fields, but they should be added if the context extension is enabled, since these fields are in the `context` object as `returned` and `matched`. 

This PR

- https://github.com/radiantearth/stac-api-spec/pull/338

added these as optional fields to any ItemCollection response, so this should be added to /search

**Comment by gadomski** [comment]
@philvarner these aren't required, though, correct? I know that the **pgstac** backend in particular does not always populate `context`, since it's expensive.

Should this issue be reworded "Add `numberReturned` and `numberMatched` fields ... **if the context extension is enabled**"?

**Comment by philvarner** [comment]
Correct, they are not required. I used "should" in the technical sense of "ought to", rather than "must" / "shall".  I rewrote to be more clear.
