### ISSUE TITLE
Response Schema undefined and not represented in Swagger

### ISSUE THREAD

**Issue by martys** [stac-utils/stac-fastapi#480]
This should display a sample result and specify the schema of the model being returned

![image](https://user-images.githubusercontent.com/210054/196419127-7ed8a47a-0557-4c2d-a825-03c7738e1bbb.png)

**Comment by gadomski** [comment]
Closing as not-an-issue, since response schemas _may_ be generated.

**Comment by martys** [comment]
> Pydantic response models are disabled by default, but may be enabled through the `Settings` object (https://github.com/stac-utils/stac-fastapi/blob/master/stac_fastapi/types/stac_fastapi/types/config.py#L27). They are disabled because pydantic validation on very large STAC returns (ex. `ItemCollection`) may take a very long time to run, slowing down API performance drastically.
> 
> Enabling response models will automatically generate return schemas but at the cost of performance.

@geospatial-jeff - could You please clarify how to enable that through settings exactly, as I fail to find any specific properties regarding it? (this might be due to my lack of experience with Python, that I can find my way around on my own)
