### ISSUE TITLE
Collections missing `type` field in Radiant Earth MLHub

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#486]
Radiant Earth MLHub is stac-fastapi, and returns a Collection without a `type` for collects, e.g.
https://api.radiant.earth/mlhub/v1/collections/umd_mali_crop_type_labels

**Comment by gadomski** [comment]
I see a type field at https://api.radiant.earth/mlhub/v1/collections/umd_mali_crop_type_labels, is this issue still valid?

**Comment by philvarner** [comment]
probably can close this -- it was either an issue with their Collection objects which was fixed or they updated stac-fastapi versions
