### ISSUE TITLE
Validating items in a collection (listing all items)

### ISSUE THREAD

**Issue by jorge-cervest** [stac-utils/stac-fastapi#491]
Hi! 

I'm working with relatively large collections (20k plus items) and I would like to validate that the pipeline I created to post all the items finished successfully.

Is there a way to check how many items has a collection or a way to list all the item? I get an error if I try to set a large limit like 30k.

Thanks.

**Comment by gadomski** [comment]
You could use [**pystac-client**](https://pystac-client.readthedocs.io/en/stable/api.html#pystac_client.ItemSearch.items) to iterate through all the pages and count them that way?

#349 has some discussion around the `"matched"` key, which _would_ give you what you wanted if it were implemented.
