### ISSUE TITLE
Add collection paging

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stac-fastapi#510]
Collection pagination was defined in https://github.com/radiantearth/stac-api-spec/pull/221. It could be useful for large catalogs (e.g. the Planetary Computer).

**Comment by vincentsarago** [comment]
in v3.0, users are able to set the request model for the `/collections` endpoint (without needing the collection-search extension), so you can now enable pagination extension for the /collections endpoint. 

Note: it's up to the user to set the correct conformance classes in the Client
