### ISSUE TITLE
Wrong CQL Text/JSON conformance classes

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/stac-fastapi#539]
I think the CQL Text/JSON conformance classes are not correct. I haven't checked the implementation myself, just base my knowledge on the MS PC API deployment and the docs: https://stac-utils.github.io/stac-fastapi/api/stac_fastapi/extensions/core/filter/filter/#filterextension

- MSPC and docs: `https://api.stacspec.org/v1.0.0-rc.1/item-search#filter:cql-text` and json equivalent
- The Filter extension indicates: `http://www.opengis.net/spec/cql2/1.0/conf/cql2-text` and json equivalent

_Originally posted by @m-mohr in https://github.com/stac-utils/stac-fastapi/issues/371#issuecomment-1458065452_

**Comment by gadomski** [comment]
@philvarner I believe @m-mohr is correct, **stac-fastapi** is doing it wrong, but if you don't mind can you double-check? E.g. I get this against the **pgstac** backend on current **main** (6db83a9c05d200d43e83c19a585fcf7f0d9e6396):

```shell
$ curl -s http://localhost:8080/conformance | jq | grep cql-text
    "https://api.stacspec.org/v1.0.0-rc.1/item-search#filter:cql-text",
```

**Comment by gadomski** [comment]
Once complicating factor, @m-mohr, is that http://www.opengis.net/spec/cql2/1.0/conf/cql2-text is a 404. So the spec itself seems to be wrong (or at least has broken dependencies). @philvarner can you advise?

**Comment by m-mohr** [comment]
OGC URIs often don't resolve, that's normal, I think. @gadomski 
Same applies for example for http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30 and http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter, which are used already.

**Comment by gadomski** [comment]
That's very weird, but OK, thanks.
