### ISSUE TITLE
Use actions to deploy Github pages (or use readthedocs)

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stac-fastapi#545]
IMO it's easier and cleaner than maintaining a `gh-pages` branch. A simple example of the workflow: https://github.com/gadomski/stac-utils-developer-guide/blob/c4bbd421778039fcbfaf753a078e1b6e0c17a3e6/.github/workflows/deploy.yaml.

Or we could use readthedocs.

**Comment by jonhealy1** [comment]
We have this workflow: https://github.com/stac-utils/stac-fastapi/blob/main/.github/workflows/deploy_mkdocs.yml
