### ISSUE TITLE
Add support for the STAC API Aggregation Extension

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stac-fastapi#567]
https://github.com/stac-api-extensions/aggregation

Implemented in stac-server, see:

* Per-collection advertisement of available aggregations: https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a/aggregations
* Requesting that aggregation: https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a/aggregate?aggregations=total_count

**Comment by jonhealy1** [comment]
Hi. Can we close this?
