### ISSUE TITLE
Remove stac-pydantic dependency

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stac-fastapi#588]
[stac-pydantic](https://github.com/stac-utils/stac-pydantic) is unmaintained and lags well behind the STAC specification. We should remove our dependency on that package.

Alternatively, **stac-pydantic** could be brought up-to-date with the current STAC spec and **pydantic** v2. This would be more work.

**Comment by thomas-maschler** [comment]
It would be great if someone could review https://github.com/stac-utils/stac-pydantic/pull/127. I am happy to make further changes if necessary.

**Comment by vincentsarago** [comment]
in 3.0 we will still depends on stac-pydantic and it seems this will continue. 

I'm going to closes this issue for now
