### ISSUE TITLE
pin geojson-pydantic to <0.6

### ISSUE THREAD

**Issue by vincentsarago** [stac-utils/stac-fastapi#589]
👇 this won't work with geojson-pydantic >0.5

https://github.com/stac-utils/stac-fastapi/blob/b9cedf353eae9aaad76c3a9a1e886bfb7c5e04ff/stac_fastapi/types/stac_fastapi/types/search.py#L206-L228

**Comment by vincentsarago** [comment]
Note: I've started a PR in stac-pydantic to pin geojson-pydantic between 0.4 and 1.0. I didn't do `<0.6` because technically the library will work with version 0.6 (while stac-fastapi won't)

https://github.com/stac-utils/stac-pydantic/pull/125

**Comment by jonhealy1** [comment]
@vincentsarago Will this issue be closed via #625 ?

**Comment by vincentsarago** [comment]
yes and no, #625 will update the dependency to stac-pydantic, but the issue with stac-fastapi and stac-pydantic is that we don't set upper bound to libraries so anyone stac-fastapi~= 2.4 will have an issue because we don't mention that it should also set a limit on pydantic (<2.0)
