### ISSUE TITLE
incorrect url in PyPI documentation

### ISSUE THREAD

**Issue by PowerChell** [stac-utils/stac-fastapi#591]
On the [PyPI documentation page for stac-fastapi](https://pypi.org/project/stac-fastapi.pgstac/), the current location URL is missing the 's' at the end of 'utils', so leads to a 404 error.

Current: 

> History
> stac-fastapi-pgstac was initially added to stac-fastapi by [developmentseed](https://github.com/developmentseed). In April of 2023, it was removed from the core stac-fastapi repository and moved to its current location (http://github.com/stac-util/stac-fastapi-pgstac).

Expected:

> History
> stac-fastapi-pgstac was initially added to stac-fastapi by [developmentseed](https://github.com/developmentseed). In April of 2023, it was removed from the core stac-fastapi repository and moved to its current location (http://github.com/stac-utils/stac-fastapi-pgstac).

**Comment by gadomski** [comment]
Fixed: https://github.com/stac-utils/stac-fastapi-pgstac/commit/92012de43bcf5709ffa9c88158c5cdb8adea543e
