### ISSUE TITLE
Cannot Import 'UndefinedType' from 'pydantic.fields'

### ISSUE THREAD

**Issue by iliion** [stac-utils/stac-fastapi#592]
The following dependencies are in a `setup.py`

    "stac_pydantic==2.0.3",
    "stac-fastapi.types==2.4.8",
    "stac-fastapi.api==2.4.8",
    "stac-fastapi.extensions==2.4.8", 

`pip install -e <dir>[dev,server]` will give me the following import error:

```
Traceback (most recent call last):
  File "/home/..../stac_fastapi/elasticsearch/app.py", line 6, in <module>
    from stac_fastapi.api.models import create_get_request_model, create_post_request_model
  File "/home/.../.venv/lib/python3.8/site-packages/stac_fastapi/api/models.py", line 9, in <module>
    from pydantic.fields import UndefinedType
ImportError: cannot import name 'UndefinedType' from 'pydantic.fields' (/home/.../.venv/lib/python3.8/site-packages/pydantic/fields.py)
```

Are there any constraints in package versions in order to make this work? whatever i do i get the above error

[Related issue](https://github.com/stac-utils/stac-fastapi/issues/588#issuecomment-1705412522)

**Comment by iliion** [comment]
ok. `UndefinedType` has become `PydanticUndefined`. I close the issue

**Comment by gadomski** [comment]
Did you have to modify your enviornment (e.g. pin dependencies) to get things to work? If so, we should uptake those changes to this repo to help others out.

**Comment by gadomski** [comment]
Re-opening as this is a pin that should be added to **stac-fastapi**.
