### ISSUE TITLE
Update to pydantic 2.0

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stac-fastapi#593]
I hear it's faster 😉

**Comment by keul** [comment]
Is this related to #588 ?

**Comment by gadomski** [comment]
Yes, #588 would probably be a blocker for this issue.

**Comment by eseglem** [comment]
As an FYI, I finally got around to updating [pycql2](https://github.com/eseglem/pycql2/tree/develop) to work with v2. If it would be useful for this update. Its in the develop branch right now and is passing all my tests + some hypothesis fuzzing. Had to do a few odd things to get v2 working, but think its in a decent spot. And happy to address any concerns with it if there are any, as well as provide any help integrating.

**Comment by thomas-maschler** [comment]
support for pydantic 2 was added in [stac-pydantic 3.0.0](https://github.com/stac-utils/stac-pydantic/releases/tag/3.0.0)

**Comment by thomas-maschler** [comment]
@bmcandr please see #625

**Comment by bmcandr** [comment]
:wave: @thomas-maschler. Thanks! I was actually asking about 588 with respect to your PR. The discussion in https://github.com/stac-utils/stac-pydantic/pull/127 _suggests_ that it's no longer a blocker on this issue, but I haven't seen confirmation. Just eager to get your PR merged 😄

**Comment by vincentsarago** [comment]
done in #625
