### ISSUE TITLE
Transaction extension inconsistency

### ISSUE THREAD

**Issue by StijnCaerts** [stac-utils/stac-fastapi#610]
The collections operations are not part of the transaction API extension (yet). But these endpoints are already implemented in `stac-fastapi`.
It would be nice if the operations are more consistent with the item operations.

For example, to update a collection, use the `PUT /collections/{collection_id}` endpoint explicitly including the collection ID.
It looks like it is also intended to be implemented like this according to this documentation snippet: https://github.com/stac-utils/stac-fastapi/blob/925a9bbc686dcb1f17808719ab9863c08b92ea36/stac_fastapi/extensions/stac_fastapi/extensions/core/transaction.py#L35-L44

However right now, the update collection endpoint doesn't include the collection ID:
https://github.com/stac-utils/stac-fastapi/blob/925a9bbc686dcb1f17808719ab9863c08b92ea36/stac_fastapi/extensions/stac_fastapi/extensions/core/transaction.py#L119-L132

**Comment by jonhealy1** [comment]
I feel like we should make a pr to fix this for now.

**Comment by jonhealy1** [comment]
https://github.com/stac-utils/stac-fastapi/pull/631/files

**Comment by jonhealy1** [comment]
Closing but feel free to re-open.
