### ISSUE TITLE
Add support for the STAC API Collection Search Extension

### ISSUE THREAD

**Issue by juliayun23** [stac-utils/stac-fastapi#615]
https://github.com/stac-api-extensions/collection-search

I noticed that [stac-browser v3.1.0](https://github.com/radiantearth/stac-browser/releases/tag/v3.1.0) has added support for Collection Search. We are using `stac-browser `on top of `stac-fastapi`. 

Just wondering whether there's any plan of adding the support for Collection Search Extension in `stac-fastapi`? Thanks.

**Comment by vincentsarago** [comment]
partially done in #736
post extension proposed in #739
