### ISSUE TITLE
Release v2.4.9

### ISSUE THREAD

**Issue by edkeeble** [stac-utils/stac-fastapi#617]
We have a few nice additions since the most recent release in June, including a new backend 🥳. It would be great to publish a new release to make these available via pypi. It will also allow downstream work for #614 to be wrapped up on [stac-fastapi-pgstac](https://github.com/stac-utils/stac-fastapi-pgstac/pull/64).

cc @gadomski

**Comment by gadomski** [comment]
https://github.com/stac-utils/stac-fastapi/releases/tag/2.4.9
