### ISSUE TITLE
how to secure STAC-FASTAPI Transaction Extension

### ISSUE THREAD

**Issue by sylar11** [stac-utils/stac-fastapi#629]
### Discussed in https://github.com/stac-utils/stac-fastapi/discussions/626

<div type='discussions-op-text'>

<sup>Originally posted by **sylar11** February 12, 2024</sup>
Hi all,
is there a way to secure the STAC-FASTAPI concerning that _Transaction Extension_ that can be dangerous if everyone can easily run from the API?
</div>

**Comment by vincentsarago** [comment]
I don't think this deserve an issue as it's already discussed in #626
