### ISSUE TITLE
Upgrade fastapi version for Content-Type Header ReDoS

### ISSUE THREAD

**Issue by juliayun23** [stac-utils/stac-fastapi#632]
There's a vulnerability reported for the `fastapi` package, in short, the affected versions (<= 0.109.0) of fastapi are prone to `Content-Type Header ReDoS (Regular expression Denial of Service)`, see details [here](https://github.com/tiangolo/fastapi/security/advisories/GHSA-qf9m-vfgh-m389).

Looks like the fastapi version this project is using is [fastapi>=0.73.0
](https://github.com/stac-utils/stac-fastapi/blob/4fb10ec6ba758f28ddef749ea7bac6fbb5963f9b/stac_fastapi/types/setup.py#L9)

Is there a plan to upgrade the `fastapi` to the patched version `0.109.1`?

**Comment by vincentsarago** [comment]
@juliayun23 fastapi is pinned to >=0.73 meaning that in should it could select `>0.109.0`

```
python -m pip install stac-fastapi.api==2.4.9
Collecting stac-fastapi.api==2.4.9
  Using cached stac_fastapi.api-2.4.9-py3-none-any.whl.metadata (1.2 kB)

...
Collecting fastapi>=0.73.0 (from stac-fastapi.types->stac-fastapi.api==2.4.9)
  Using cached fastapi-0.109.2-py3-none-any.whl.metadata (25 kB)
...
Successfully installed anyio-4.2.0 attrs-23.2.0 brotli-1.1.0 brotli-asgi-1.4.0 click-8.1.7 exceptiongroup-1.2.0 fastapi-0.109.2 geojson-pydantic-0.6.3 idna-3.6 iso8601-2.1.0 pydantic-1.10.14 pystac-1.9.0 python-dateutil-2.8.2 python-dotenv-1.0.1 six-1.16.0 sniffio-1.3.0 stac-fastapi.api-2.4.9 stac-fastapi.types-2.4.9 stac-pydantic-2.0.3 starlette-0.36.3 typing-extensions-4.9.0
```

**Comment by vincentsarago** [comment]
we now have fastapi pinned to >0.111.0
