### ISSUE TITLE
Cannot use custom fields in Items

### ISSUE THREAD

**Issue by giorgiobasile** [stac-utils/stac-fastapi#646]
This issue follows: stac-utils/stac-fastapi-pgstac#93

In a nutshell, while trying to upload Items adhering to the [Rendering](https://github.com/stac-extensions/render) extension using the `POST /collection/{collection_id}/items` API, I noticed that any additional custom field set at the Item level - not as a _property_ - would be ignored by the transactional endpoints. This would basically hinder the ability to work with any extension that mandates the usage of additional fields at the Item level.

The payload I'm trying to use looks like:

```json
{
    "type": "Feature",
    "stac_version": "1.0.0",
    "id": "nexgddp-storm-global-2080-rcp85",
    "properties": {...},
    "geometry": {...},
    "links": [...],
    "assets": {...},
    "bbox": [...],
    "stac_extensions": [
        "https://stac-extensions.github.io/render/v1.0.0/schema.json"
    ],
    "renders": {
        "webmap": {
            "title": "Storm risk (2080, RCP8.5)",
            "colormap_name": "blues",
            "return_mask": true,
        }
    },
}
```

but the API responds with 200 OK and a similar Item, but without the `renders` object. The jsonb blob stored in the database doesn't have that field either.

With the help of @jonhealy1 we pinpointed the issue in [this](https://github.com/stac-utils/stac-fastapi/blob/4fb10ec6ba758f28ddef749ea7bac6fbb5963f9b/stac_fastapi/types/stac_fastapi/types/stac.py#L59-L71) pydantic model, that does not allow for [extra](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.extra) fields to be carried along during [parsing](https://github.com/stac-utils/stac-fastapi/blob/4fb10ec6ba758f28ddef749ea7bac6fbb5963f9b/stac_fastapi/extensions/stac_fastapi/extensions/core/transaction.py#L18) happening in the transactional endpoints.

A potential solution would be to just specify: 

```python
class Item(TypedDict, total=False):
    """STAC Item."""
  
    model_config = ConfigDict(extra='allow')
  ...
```  

and I'd be happy to send a PR, but I'm not sure whether that would actually solve the issue and what kinds of side-effects that could have, also for the other non-transactional endpoints. Any thoughts?

**Comment by jonhealy1** [comment]
Hi @giorgiobasile. I think the correct place to address this is actually in the extension itself. If you look [here](https://github.com/radiantearth/stac-spec/blob/fd8fb4e3cf0b6c4a0fe74822accbc1725a92f92a/extensions/README.md?plain=1#L113-L114) it says: "Additional attributes relating to an [Item](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md) should be added into the Item Properties object, rather than directly in the Item object." The `renders` field should be inside the item properties I think.

**Comment by giorgiobasile** [comment]
> Hi @giorgiobasile. I think the correct place to address this is actually in the extension itself. If you look [here](https://github.com/radiantearth/stac-spec/blob/fd8fb4e3cf0b6c4a0fe74822accbc1725a92f92a/extensions/README.md?plain=1#L113-L114) it says: "Additional attributes relating to an [Item](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md) should be added into the Item Properties object, rather than directly in the Item object." The `renders` field should be inside the item properties I think.

@jonhealy1 that's a great find, I understand. If you agree, I would consider the issue closed, and I'll open another one on the Rendering repo, to see whether they would consider changing it according to that recommendation.

Thank you again for helping out, appreciated!

**Comment by m-mohr** [comment]
I think renders should be in properties, not on the top-level

**Comment by giorgiobasile** [comment]
Thanks @m-mohr, I would just also mention this section of the spec: https://github.com/radiantearth/stac-spec/tree/master/extensions#use-of-arrays-and-objects

So according to the document, there would be the nesting issue to be considered if `renders` is a property, but not if it stays as a top-level object. But maybe there are other factors to be considered, and you definitely know best!

**Comment by giorgiobasile** [comment]
> Maybe renders can be flattened into a number of properties?

The problem I see is that `renders` is a `Map<string, Render>`, so it supports multiple, arbitrary `Render` objects to be specified, so very difficult to flatten imho.

**Comment by m-mohr** [comment]
The nesting is only a niche issue for old GeoJSON tooling. Other than extensions use nested map without issues. The bigger issue is obviously to add top level properties to Items ;)
