### ISSUE TITLE
PUT "/collections/{collection_id}" throws "update_collection() missing 1 required positional argument: 'collection'"

### ISSUE THREAD

**Issue by avbentem** [stac-utils/stac-fastapi#665]
#630 fixed the update collection REST endpoint in the "transactions" extension, to properly include the collection's id in `/collections/{collection_id}`. Nice.

However, [when the endpoint is registered](https://github.com/stac-utils/stac-fastapi/blob/2e14348e9e9d37904b065156c8155b57de99e3b9/stac_fastapi/extensions/stac_fastapi/extensions/core/transaction.py#L131) it still only expects a Collection in the JSON payload, without defining the new URL segment. This makes the first `update_collection` argument `collection_id` being passed the full JSON payload, and makes `collection` being empty.

This throws `update_collection() missing 1 required positional argument: 'collection'`.

I'll create a PR with a fix.

**Comment by jonhealy1** [comment]
Hi @avbentem. Thanks for this. What stac-fastapi backend are you using?

**Comment by avbentem** [comment]
Hi @jonhealy1 sorry for only seeing your question today. I'm not actually using any backend yet. (I'll likely use a bespoke one, combing Google cloud storage with PostGIS.) But I ran into this bug when setting up a basic project structure, that basically only implements the abstract methods to print the requests. (Kind of like in the tests I added.)

Wondering why you're asking. Do you think that some of the `stac-utils` provided backends (like [stac-fastapi-pgstac](https://github.com/stac-utils/stac-fastapi-pgstac) or [stac-fastapi-sqlalchemy](https://github.com/stac-utils/stac-fastapi-sqlalchemy)) would not suffer from this bug? If that would be the case then I'd guess that those backends are not using the abstract classes that this very `stac-fastapi` provides?

**Comment by jonhealy1** [comment]
Ok thanks for the clarification. stac-fastapi-pgstac and stac-fastapi-elasticsearch-opensearch seem to be fine. You may be right - something to look into.
