### ISSUE TITLE
Integration testing with key stac-fastapi backends

### ISSUE THREAD

**Issue by jonhealy1** [stac-utils/stac-fastapi#671]
Before releasing a new version we should run integration tests against stac-fastapi-pgstac and stac-fastapi-elasticsearch.

**Comment by jonhealy1** [comment]
How about setting up integration tests with GitHub Actions that would run against both the stac-fastapi-elasticsearch and stac-fastapi-pgstac backends whenever we make significant changes to stac-fastapi. We could do this either by triggering the tests manually, which gives us control over when they run, or automatically on pushes to release/** branches to catch issues earlier. What do you all think about this? Would it be better to keep the tests manual for now, or should we automate them for certain branches? This way, we could ensure everything meshes well before any new release.

**Comment by vincentsarago** [comment]
The issue might be that both backend evolves at different speed and it might be hard to get the test running. I would prefer if we do a simple `fake` client like we do in https://github.com/stac-utils/stac-fastapi/blob/main/stac_fastapi/extensions/tests/test_transaction.py

**Comment by jonhealy1** [comment]
The workflow would be complicated. What if it's just something with workflow dispatch that we can run manually just to see what kind of damage the changes cause? It might help us from needing too many bug fixes. The fake client is good but it won't catch every bug.

**Comment by jonhealy1** [comment]
The tests themselves would just be the tests in the elasticsearch and pgstac backend repos
