### ISSUE TITLE
Remove dependency between Aggregate and Filter extensions 

### ISSUE THREAD

**Issue by vincentsarago** [stac-utils/stac-fastapi#715]
@jamesfisher-gis sorry I'm just realizing this now but I don't think we should do this, at least I don't see in the `aggregate` extension why the `filter` attributes should be enabled with the `aggregations` ones. 

I think it will be up to the implementers to add the `filter` extension and also handle them in the client.

_Originally posted by @vincentsarago in https://github.com/stac-utils/stac-fastapi/pull/684#discussion_r1651218182_

**Comment by vincentsarago** [comment]
https://github.com/stac-utils/stac-fastapi/blob/8f400e18f361132b92f32d8e3fd62787b3276adc/stac_fastapi/extensions/stac_fastapi/extensions/core/aggregation/request.py#L24

also realizing that in ☝️ we use `attr.ib` instead of pydantic.Field

**Comment by jamesfisher-gis** [comment]
Hey. That makes sense.

I have a couple other small bug fixes for aggregation. I will submit a PR today that removes the Filter extension dependency.
