### ISSUE TITLE
/collections/{collection_id}/items Token Pagination broken in 3.0.0b1, 3.0.0b2

### ISSUE THREAD

**Issue by captaincoordinates** [stac-utils/stac-fastapi#731]
Minimum repro case [here](https://github.com/captaincoordinates/stac-fastapi-3.0.0b1-pagination-issue).

`AsyncBaseCoreClient#item_collection` receives a `None` token in 3.0.0b1 and 3.0.0b2 when token is provided as a query string parameter. The minimum repro case asserts `token is not None` [here](https://github.com/captaincoordinates/stac-fastapi-3.0.0b1-pagination-issue/blob/559ab27ee3ae08aae12f66372fb9051cc0fc1170/src/core.py#L33) when hitting `/collections/collection_id/items?token=query-string-token-value`. The test passes in 3.0.0a4 but fails in 3.0.0b1 or 3.0.0b2.

To test execute [scripts/test.sh](https://github.com/captaincoordinates/stac-fastapi-3.0.0b1-pagination-issue/blob/559ab27ee3ae08aae12f66372fb9051cc0fc1170/scripts/test.sh). The test hits the same endpoint across three different versions of stac-fastapi:
- 3.0.0a4
- 3.0.0b1
- 3.0.0b2

I assume this is related to one or more of #714, #717, #718, #729.

**Comment by vincentsarago** [comment]
thanks for opening the issue @captaincoordinates

have you read: 
- https://github.com/stac-utils/stac-fastapi/blob/main/CHANGES.md#removed
- https://stac-utils.github.io/stac-fastapi/migrations/v3.0.0/#pagination-extension ? 

As mentioned in the changelog and in the migration guide, for the `/items` endpoint you now need to set the `GET` model when constructing the StacApi object 

```python
# before
stac=StacApi(
    pagination_extension=TokenPaginationExtension,
    extension=[TokenPaginationExtension]
)

# now
items_get_request_model = create_request_model(
    "ItemCollectionURI",
    base_model=ItemCollectionUri,
    mixins=[TokenPaginationExtension().GET],
)

stac=StacApi(
    extension=[TokenPaginationExtension],
    items_get_request_model=items_get_request_model,
)
```

**Comment by captaincoordinates** [comment]
That's great, thanks @vincentsarago. Sorry for missing the docs on this, I wasn't expecting to need them from alpha to beta.

**Comment by vincentsarago** [comment]
@captaincoordinates yeah sorry about that, this changed came late into the dev phase, we decided to go from alpha to beta to raise awareness about change between versions but we could have make this better I guess
