### ISSUE TITLE
Maximum search limit hardcoded to 10000

### ISSUE THREAD

**Issue by remicres** [stac-utils/stac-fastapi#747]
Currently the max search limit value is hardcoded to 10000 [here](https://github.com/stac-utils/stac-fastapi/blob/main/stac_fastapi/types/stac_fastapi/types/search.py#L20).

It could be a nice to set a different value, because 10000 can be huge in some cases, depending how heavy items are.

**Comment by vincentsarago** [comment]
this is discussed over https://github.com/stac-utils/stac-fastapi/discussions/737
