### ISSUE TITLE
Add STAC_API_VERSION in landing page

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/stac-fastapi#761]
I'm a bit confused by https://github.com/stac-utils/stac-fastapi/blob/3c4ce2e0b8616d388b94a9cfb2a28e5d44ada29a/stac_fastapi/types/stac_fastapi/types/core.py#L271

STAC_API_VERSION is meant to be the STAC API version (i.e. stac-api-spec), right?

But the STAC API Version is different to the STAC version. We try to expose STAC 1.1.0 items and update the landing page to 1.1.0, too, but setting the STAC_API_VERSION seems incorrect, because there is no 1.1.0 version for the API.

**Comment by m-mohr** [comment]
Maybe it's also valuable to have STAC_API_VERSION if you want to switch between (bugfix) API versions, but having a separate STAC_VERSION is certainly a good idea. Do you think it makes sense to also have a STAC_API_VERSION? (e.g. to update to easily/quickly STAC API 1.0.1 once released?)

**Comment by vincentsarago** [comment]
the stac-api-specification only mention `stat-version` in the landing model 

https://github.com/radiantearth/stac-api-spec/blob/bab9bdf22b54cd119e931859b0da13f42091abb8/core/commons.yaml#L50-L51

 but extra values are allowed https://github.com/stac-utils/stac-pydantic/blob/main/stac_pydantic/catalog.py#L22

**Comment by vincentsarago** [comment]
I've created #762

adding `stac_api_version` is a bit more complication because it will involve more changes and a new Minor version so if we really want this we should create a specific issue for it

**Comment by m-mohr** [comment]
Not feeling strongly about STAC_API_VERSION, we can just fix the actual issue for now. Thanks for creating the PR!

**Comment by vincentsarago** [comment]
closing this for now because it's not a spec requirement
