### ISSUE TITLE
allow more geometry types for search

### ISSUE THREAD

**Issue by vincentsarago** [stac-utils/stac-fastapi#87]
It seems that right now only Polygon (POST) and bbox (GET) are supported 
https://github.com/arturo-ai/arturo-stac-api/blob/7d4c9572981e935de2521441878f3ffb78f6b9b7/stac_api/clients/postgres/core.py#L321-L327

https://github.com/arturo-ai/arturo-stac-api/blob/master/stac_api/models/schemas.py#L228-L235

the STAC API specs says:
> Searches items by performing intersection between their geometry and provided GeoJSON geometry. All GeoJSON geometry types must be supported.
ref: 
 https://github.com/radiantearth/stac-api-spec/blob/f64a08235cb0ae04dfdb37bd8d6940c3814d057c/item-search/README.md#query-parameter-table

cc @kylebarron @geospatial-jeff

**Comment by jonhealy1** [comment]
@vincentsarago I don't think is an issue. I added some test cases with https://github.com/stac-utils/stac-fastapi/pull/264 to show that other geojson geometries are working. Maybe this was fixed at some point? I think that naming this poly: poly = shape(search_request.intersects) is confusing.

**Comment by vincentsarago** [comment]
Yes I think this was fixed
